#+TITLE: Development Environment (UnifiedViews 2.1.3)

* Introduction

  The following tools are included in this environment

  - [[http://localhost:28080/unifiedviews][Unified Views 2.1.3]]
  - [[http://localhost:8890/conductor][Virtuoso Conductor]]/[[http://localhost:1111/sparql][Virtuoso Sparql Endpoint]]
  - [[file:///var/local/yasgui/blank.html][Yasgui]]

* Environment Details
  
  - Ubuntu 15.04
  - MySQL 5.6
  - Firefox

* Account Details
** Unified Views Account Details
- The homepage for unified views is: http://localhost:28080/unifiedviews

  - Login account  : /admin/
 
  - Login password : /test/

Unified-views functions should then be accessible.

** Accessing Virtuoso
The tenforce/virtuoso Docker image installed and should be accessible
on: http://localhost:8890/conductor, access details are:

- Login account  : /dba/
  
- Login password : /root/

The same details should be used when connecting in the DPU within
UnifiedViews.

* Development Environment

  - Files in /vagrant are shared with the host system,
    so backup of pipelines, etc. need to be moved there.

  - /vagrant/virtuoso will contain the database (will be
    created once).

** DPU Development
In the /vagrant environment, the Plugin-DevEnv is also cloned
from the git repository. The DevEnv has been installed, so 
the following should work.

#+BEGIN_SRC bash
cd /vagrant
mvn archetype:generate
--> 1360 is the eu.unifiedviews archetype
--> Fill in other values as required for your-project
cd your-project
mvn package
#+END_SRC

The result of this will be a package which can be imported into
UnifiedViews. More details: [[https://docs.google.com/document/d/1QDImj2SO5XOasG-K9EV1wdzgnZXY8jJPBSAG5J84T_Q/edit#][DPU Creation Tutorial]]

** YASGUI
Is also included using as a SPARQL querying tool.

#BEGIN_SRC
  file:///var/local/yasgui/blank.html
#END_SRC

