#+TITLE: Vagrant UV 2.x on Ubuntu 15.04

* Introduction
This will build an Ubuntu 15.04 based VM including the latest 2.x
version of the [[http://unifiedviews.eu/][UnifiedViews]] packages which has been tested. The system
will run the following main software components:

- Ubuntu 15.04
- Unified Views 2.1.3 ([[https://github.com/UnifiedViews][Github]])
- Docker ([[https://www.docker.com][Homepage]])
- Virtuoso ([[https://github.com/tenforce/docker-virtuoso][tenforce docker]])
- MySQL 5.6 ([[https://www.mysql.com][Homepage]])
- Tomcat7 & Java7 (Installed packages, assuming [[https://grips.semantic-web.at/pages/viewpage.action?pageId=50929588][DPU]] development)
- YASGUI is also installed.

It has been tested using the setup described in "Before starting".

*NOTES:*
- Newer available versions can be tested by updating the VERSION
  indicator in the bootstrap.sh file (and rebuilding the VM).
- Guest addition handling packages are also installed (as well as 
  some of the more common text editors - emacs, nano and vim).
- When using this for developing additional components/pipelines, they
  *must* be periodically backed up into the /vagrant directory which
  is shared with the host machine.
- THIS MACHINE SHOULD NOT BE CONNECTED TO THE INTERNET WITHOUT FIRST
  CHANGING *ALL* THE DEFAULT ACCOUNT/PASSWORD DETAILS.

* Before Starting
The two main components which have to be installed on the host machine
are:

    - VirtualBox - 5.0.6 (https://www.virtualbox.org)
    - Vagrant - 1.7.4 (https://www.vagrantup.com/)

There is also a need for a command-line tool such as bash, shell, etc
and that the paths are set correctly for 'vagrant' to be
executable. These are the latest versions which have been tested
(prior versions will not be tested). On Windows, [[www.cygwin.org][cygwin]] or [[https://git-for-windows.github.io/][git bash]] could be
installed which will provide bash along with an assortment of other
GNU open-source tools.

Download "ojdbc7.jar" from the Oracle site [1]. It is to be placed in
the directory with the VagrantFile (once downloaded).

[1] http://www.oracle.com/technetwork/database/features/jdbc/jdbc-drivers-12c-download-1958347.html

* Building the VM
On the command line:

- *git clone https://github.com/tenforce/vagrant-unifiedviews2.x-ubuntu15.04.git*
- *cd vagrant-unifiedviews2.x-ubuntu15.04*
- *vagrant plugin install vagrant-vbguest*
- *vagrant up*
  Possibly select you network interface connection point
  This will take a *long* time the first time

Then to make sure the GUI interface is usable from the virtual machine

- *vagrant halt*
- *vagrant up*

Then it should be possible to use the virtual machine:
 
- Login password: /vagrant/

- Select the *firefox* web-browser

  Normally, this should present you a homepage from which you can
  access the installed software.

- The homepage for unified views is: http://localhost:28080/unifiedviews

  - Login account  : /admin/
 
  - Login password : /test/

Unified-views functions should then be accessible.

* Accessing Virtuoso
The tenforce/virtuoso Docker image installed and should be accessible
on: http://localhost:8890/conductor, access details are:

- Login account  : /dba/
  
- Login password : /root/

The same details should be used when connecting in the DPU within
UnifiedViews.

* Development Environment
*NOTE:* Development work needs to be done in /vagrant (create a
sub-directory). This directory will not be cleaned if a *vagrant
destroy* is issued (while any other VM directory).

** DPU Development
In the /vagrant environment, the Plugin-DevEnv is also cloned
from the git repository. The DevEnv has been installed, so 
the following should work.

#+BEGIN_SRC bash
cd /vagrant
mvn archetype:generate
--> 1360 is the eu.unifiedviews archetype
--> Fill in other values as required for your-project
cd your-project
mvn package
#+END_SRC

The result of this will be a package which can be imported into
UnifiedViews. More details: [[https://docs.google.com/document/d/1QDImj2SO5XOasG-K9EV1wdzgnZXY8jJPBSAG5J84T_Q/edit#][DPU Creation Tutorial]]

** YASGUI
Is also included using as a SPARQL querying tool.

#BEGIN_SRC
  file:///var/local/yasgui/blank.html
#END_SRC
* Notes:
- Depending on the underlying system, it seems that the network
  connections settings sometimes cause problems (*halt*, wait a while
  and *up* again, normally clears the problem).
- some freezes have been observed.
